- hosts: ios102
  gather_facts: false
  vars:
    ansible_python_interpreter: python

  roles:
  - operating_state
  tasks:
  - name: "ios.interfaces: show interfaces"
    cli_parse_transform:
      engine: "pyats"
      network_os: iosxe
      commands:
        - command: "show interfaces"
          set_fact: True
    register: output
  - debug:
      var: output