- name: "ios.arp: show arp"
  cli_parse_transform:
    engine: "pyats"
    network_os: iosxe
    commands:
      - command: "show arp"
        set_fact: True
        transform:
        - name: set_root_key
          key: arp
        - name: set_root_key
          key: "{{ fact_key }}"
