- name: "ios.version: show version"
  cli_parse_transform:
    engine: "pyats"
    network_os: iosxe
    ignore_parser_errors: True
    commands:
      - command: "show version"
        set_fact: True
        transform:
        - name: set_root_key
          key: version
        - name: set_root_key
          key: "{{ fact_key }}"
