- name: Load the specific state gatherer
  include_tasks: "{{ item }}"
  with_first_found:
  - "includes/{{ ansible_network_os }}/{{ engine }}/{{ gather_one }}.yaml"
  - "includes/unsupported_gather.yaml"
