---
- name: "nxos.arp: show ip arp vrf all"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show ip arp vrf all"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: stats
          only_stats: "{{ only_stats }}"
          keys:
          - intf-out
          - vrf-name-out
        - name: set_root_key
          key: arp
        - name: set_root_key
          key: "{{ fact_key }}"
