---
- name: "nxos.mac: show mac address-table"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show mac address-table"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: address_table
        - name: set_root_key
          key: mac
        - name: set_root_key
          key: "{{ fact_key }}"
  when: not only_stats
