- name: "nxos.system: show version"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show version"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
          plural: true
        - name: set_root_key
          key: version
        - name: set_root_key
          key: "{{ fact_key }}"
  when: not only_stats
