---
- name: "nxos.vlan: show vlan"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vlan"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: "stats"
          only_stats: "{{ only_stats }}"
          keys:
          - vlanshowbr-vlanstate
        - name: set_root_key
          key: vlan
        - name: set_root_key
          key: "{{ fact_key }}"
