- name: "eos.arp: show ip arp vrf all"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show ip arp vrf all"
        set_fact: True
        transform:
        - name: camel_to_snake
        - name: set_root_key
          key: ip_arp_vrf_all
        - name: set_root_key
          key: "{{ fact_key }}"
