- name: "eos.vlan: show vlan"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vlan"
        set_fact: True
        transform:
        - name: camel_to_snake
        - name: set_root_key
          key: vlan
        - name: set_root_key
          key: "{{ fact_key }}"
