- name: Get the native transform capabilities
  nxos_facts:
    gather_subset:
    - '!all'
  when: gather_states_engine is not defined

- name: Set the engine for nxos
  set_fact:
    engine: "{% if gather_states_engine is defined %}{{ gather_states_engine }}
             {%- elif ansible_net_version.split('.')[0]|int > 7 %}json
             {%- else %}xml{% endif %}"
